<?xml version="1.0" encoding="utf-8" standalone="yes"?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"><channel><title>Cuda on Svtter's Blog</title><link>https://svtter.cn/categories/cuda/</link><description>Recent content in Cuda on Svtter's Blog</description><generator>Hugo -- gohugo.io</generator><language>zh-cn</language><lastBuildDate>Tue, 04 Mar 2025 18:07:13 +0800</lastBuildDate><atom:link href="https://svtter.cn/categories/cuda/index.xml" rel="self" type="application/rss+xml"/><item><title>Torchvision Cuda Problem.md</title><link>https://svtter.cn/p/torchvision-cuda-problem.md/</link><pubDate>Tue, 04 Mar 2025 18:07:13 +0800</pubDate><guid>https://svtter.cn/p/torchvision-cuda-problem.md/</guid><description>&lt;p&gt;记录一下 torchvision 遇到的问题&lt;/p&gt;
&lt;div class="highlight"&gt;&lt;div class="chroma"&gt;
&lt;table class="lntable"&gt;&lt;tr&gt;&lt;td class="lntd"&gt;
&lt;pre tabindex="0" class="chroma"&gt;&lt;code&gt;&lt;span class="lnt"&gt;1
&lt;/span&gt;&lt;/code&gt;&lt;/pre&gt;&lt;/td&gt;
&lt;td class="lntd"&gt;
&lt;pre tabindex="0" class="chroma"&gt;&lt;code class="language-fallback" data-lang="fallback"&gt;&lt;span class="line"&gt;&lt;span class="cl"&gt;torch.cuda.DeferredCudaCallError: CUDA call failed lazily at initialization with error: device &amp;gt;= 0 &amp;amp;&amp;amp; device &amp;lt; num_gpus INTERNAL ASSERT FAILED at &amp;#34;/opt/conda/conda-bld/pytorch_1712608839953/work/aten/src/ATen/cuda/CUDAContext.cpp&amp;#34;:50, please report a bug to PyTorch. device=, num_gpus=
&lt;/span&gt;&lt;/span&gt;&lt;/code&gt;&lt;/pre&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;
&lt;/div&gt;
&lt;/div&gt;&lt;p&gt;我调整了代码，遇到了这个问题，结果是因为引入了 &lt;code&gt;from torchvision import transforms&lt;/code&gt;。&lt;/p&gt;
&lt;p&gt;这个问题可能是 nvidia 驱动问题导致的。解决这个问题，最好的方法是改一下 torch 的版本，找到一个和驱动接近的。&lt;/p&gt;
&lt;p&gt;重新安装 nvidia 驱动付出的代价比较大。&lt;/p&gt;</description></item></channel></rss>